### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by niedzielski**
Copy .gitignore from https://github.com/github/gitignore/blob/master/Android.gitignore and add Android Studio files.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by niedzielski** [comment]
Submitted CLA!

**Comment by anothem** [comment]
@niedzielski, could you please submit the CLA again? The heroku build doesn't seem to find it. Thanks!

**Comment by niedzielski** [comment]
Weird, I just tried to and it says:

    You previously signed this CLA on:
    Sun Jan 18 2015 20:39:09 GMT+0000 (UTC)

Can you try again?

**Comment by anothem** [comment]
Sorry for the complication. I've verified the CLA, it's all good (even if the build doesn't like it). But there's a conflict, so I can't merge :) Fix the conflict and it's merged! Thanks for the contribution!

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by niedzielski** [comment]
I've rebased (woo!). Please note, I've omitted `/out/`. The file history is not descriptive as to why this ignore was added and there are no comments. I believe it was included by mistake but will put it back if needed.

**Pull request merged**
